[package]
name = "async-socket"
version = "0.1.0"
authors = ["Tate, Hongliang Tian <tate.thl@antfin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(not(sgx))'.dependencies]
atomic = "0.5.0"
bitflags = "1.2"
libc = "0.2"
slab = { path = "../slab" }
io_uring_callback = { path = "../io-uring-callback" }

[target.'cfg(sgx)'.dependencies]
atomic = "0.5.0"
bitflags = "1.2"
slab = { path = "../slab" }
io_uring_callback = { path = "../io-uring-callback" }
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["backtrace"] }
sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
untrusted_allocator = { path = "../untrusted_allocator" }

[dev-dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
futures = { version = "0.3", default-features = false }
async_rt = { path = "../async-rt" } 